insert into "FACTURA" (id ,concepto , importe , numeroserie ,numerofactura , nifemisor , nombreemisor , nifreceptor , nombrereceptor,  numaries, numface ,puntoentrada, numregistrocontable , estado ,fechapresentacion , fechaemision , solanulacion) values (1 ,'Factura 1 de prueba', 1500 , '00001' , 'FACT-01' , '48816258T' , 'el emisor' , '00000000T' , 'el receptor' , 'AR00001' , 'FAC00001' , 'PUEF' , '00001' , 'RECIBIDA' , sysdate , sysdate , 'NO');
insert into "FACTURA" (id ,concepto , importe , numeroserie ,numerofactura , nifemisor , nombreemisor , nifreceptor , nombrereceptor,  numaries, numface ,puntoentrada, numregistrocontable , estado ,fechapresentacion , fechaemision , solanulacion) values (2 ,'Factura 2 de prueba', 1500 , '00002' , 'FACT-02' , '56995658Y' , 'el emisor' , '00000000T' , 'el receptor' , 'AR00002' , 'FAC00002' , 'PUEF' , '00001' , 'RECIBIDA' , sysdate , sysdate , 'NO');
insert into "FACTURA" (id ,concepto , importe , numeroserie ,numerofactura , nifemisor , nombreemisor , nifreceptor , nombrereceptor,  numaries, numface ,puntoentrada, numregistrocontable , estado ,fechapresentacion , fechaemision , solanulacion) values (3 ,'Factura 3 de prueba', 1500 , '00003' , 'FACT-03' , '48816258T' , 'el emisor' , '00000000T' , 'el receptor' , 'AR00003' , 'FAC00003' , 'FACE' , '00001' , 'RECIBIDA' , sysdate , sysdate , 'NO');
insert into "FACTURA" (id ,concepto , importe , numeroserie ,numerofactura , nifemisor , nombreemisor , nifreceptor , nombrereceptor,  numaries, numface ,puntoentrada, numregistrocontable , estado ,fechapresentacion , fechaemision , solanulacion) values (4 ,'Factura 4 de prueba', 1500 , '00004' , 'FACT-04' , '48816258T' , 'el emisor' , '00000000T' , 'el receptor' , 'AR00004' , 'FAC00004' , 'PUEF' , '00001' , 'RECIBIDA' , sysdate , sysdate , 'NO');
insert into "FACTURA" (id ,concepto , importe , numeroserie ,numerofactura , nifemisor , nombreemisor , nifreceptor , nombrereceptor,  numaries, numface ,puntoentrada, numregistrocontable , estado ,fechapresentacion , fechaemision , solanulacion) values (5 ,'Factura 5 de prueba', 1500 , '00005' , 'FACT-05' , '56995658Y' , 'el emisor' , '00000000T' , 'el receptor' , 'AR00005' , 'FAC00005' , 'PUEF' , '00001' , 'RECIBIDA' , sysdate , sysdate , 'NO');
insert into "FACTURA" (id ,concepto , importe , numeroserie ,numerofactura , nifemisor , nombreemisor , nifreceptor , nombrereceptor,  numaries, numface ,puntoentrada, numregistrocontable , estado ,fechapresentacion , fechaemision , solanulacion) values (6 ,'Factura 6 de prueba', 1500 , '00006' , 'FACT-06' , '48816258T' , 'el emisor' , '00000000T' , 'el receptor' , 'AR00006' , 'FAC00006' , 'PUEF' , '00001' , 'RECIBIDA' , sysdate , sysdate , 'NO');
insert into "FACTURA" (id ,concepto , importe , numeroserie ,numerofactura , nifemisor , nombreemisor , nifreceptor , nombrereceptor,  numaries, numface ,puntoentrada, numregistrocontable , estado ,fechapresentacion , fechaemision , solanulacion) values (7 ,'Factura 7 de prueba', 1500 , '00007' , 'FACT-07' , '48816258T' , 'el emisor' , '00000000T' , 'el receptor' , 'AR00007' , 'FAC00007' , 'PUEF' , '00001' , 'RECIBIDA' , sysdate , sysdate , 'NO');
insert into "FACTURA" (id ,concepto , importe , numeroserie ,numerofactura , nifemisor , nombreemisor , nifreceptor , nombrereceptor,  numaries, numface ,puntoentrada, numregistrocontable , estado ,fechapresentacion , fechaemision , solanulacion) values (8 ,'Factura 8 de prueba', 1500 , '00008' , 'FACT-08' , '56995658Y' , 'el emisor' , '00000000T' , 'el receptor' , 'AR00008' , 'FAC00008' , 'FACE' , '00001' , 'RECIBIDA' , sysdate , sysdate , 'NO');
insert into "FACTURA" (id ,concepto , importe , numeroserie ,numerofactura , nifemisor , nombreemisor , nifreceptor , nombrereceptor,  numaries, numface ,puntoentrada, numregistrocontable , estado ,fechapresentacion , fechaemision , solanulacion) values (9 ,'Factura 9 de prueba', 1500 , '00009' , 'FACT-09' , '48816258T' , 'el emisor' , '00000000T' , 'el receptor' , 'AR00009' , 'FAC00009' , 'PUEF' , '00001' , 'RECIBIDA' , sysdate , sysdate , 'NO');
insert into "FACTURA" (id ,concepto , importe , numeroserie ,numerofactura , nifemisor , nombreemisor , nifreceptor , nombrereceptor,  numaries, numface ,puntoentrada, numregistrocontable , estado ,fechapresentacion , fechaemision , solanulacion) values (10 ,'Factura 10 de prueba', 1500 , '00010' , 'FACT-10' , '48816258T' , 'el emisor' , '00000000T' , 'el receptor' , 'AR00010' , 'FAC00010' , 'PUEF' , '00001' , 'RECIBIDA' , sysdate , sysdate , 'NO');
insert into "FACTURA" (id ,concepto , importe , numeroserie ,numerofactura , nifemisor , nombreemisor , nifreceptor , nombrereceptor,  numaries, numface ,puntoentrada, numregistrocontable , estado ,fechapresentacion , fechaemision , solanulacion) values (11,'Factura 11 de prueba', 1500 , '00011' , 'FACT-11' , '56995658Y' , 'el emisor' , '00000000T' , 'el receptor' , 'AR00011' , 'FAC00011' , 'FACE' , '00001' , 'RECIBIDA' , sysdate , sysdate , 'NO');
insert into "FACTURA" (id ,concepto , importe , numeroserie ,numerofactura , nifemisor , nombreemisor , nifreceptor , nombrereceptor,  numaries, numface ,puntoentrada, numregistrocontable , estado ,fechapresentacion , fechaemision , solanulacion) values (12 ,'Factura 12 de prueba', 1500 , '00012' , 'FACT-12' , '48816258T' , 'el emisor' , '00000000T' , 'el receptor' , 'AR00012' , 'FAC00012' , 'PUEF' , '00001' , 'RECIBIDA' , sysdate , sysdate , 'NO');
insert into "FACTURA" (id ,concepto , importe , numeroserie ,numerofactura , nifemisor , nombreemisor , nifreceptor , nombrereceptor,  numaries, numface ,puntoentrada, numregistrocontable , estado ,fechapresentacion , fechaemision , solanulacion) values (13 ,'Factura 13 de prueba', 1500 , '00013' , 'FACT-13' , '56995658Y' , 'el emisor' , '00000000T' , 'el receptor' , 'AR00013' , 'FAC00013' , 'FACE' , '00001' , 'RECIBIDA' , sysdate , sysdate , 'NO');
insert into "FACTURA" (id ,concepto , importe , numeroserie ,numerofactura , nifemisor , nombreemisor , nifreceptor , nombrereceptor,  numaries, numface ,puntoentrada, numregistrocontable , estado ,fechapresentacion , fechaemision , solanulacion) values (14 ,'Factura 14 de prueba', 1500 , '00014' , 'FACT-14' , '48816258T' , 'el emisor' , '00000000T' , 'el receptor' , 'AR00014' , 'FAC00014' , 'PUEF' , '00001' , 'RECIBIDA' , sysdate , sysdate , 'NO');
insert into "FACTURA" (id ,concepto , importe , numeroserie ,numerofactura , nifemisor , nombreemisor , nifreceptor , nombrereceptor,  numaries, numface ,puntoentrada, numregistrocontable , estado ,fechapresentacion , fechaemision , solanulacion) values (15 ,'Factura 15 de prueba', 1500 , '00015' , 'FACT-15' , '48816258T' , 'el emisor' , '00000000T' , 'el receptor' , 'AR00015' , 'FAC00015' , 'FACE' , '00001' , 'RECIBIDA' , sysdate , sysdate , 'NO');
insert into "FACTURA" (id ,concepto , importe , numeroserie ,numerofactura , nifemisor , nombreemisor , nifreceptor , nombrereceptor,  numaries, numface ,puntoentrada, numregistrocontable , estado ,fechapresentacion , fechaemision , solanulacion) values (16 ,'Factura 16 de prueba', 1500 , '00016' , 'FACT-16' , '48816258T' , 'el emisor' , '00000000T' , 'el receptor' , 'AR00016' , 'FAC00016' , 'PUEF' , '00001' , 'RECIBIDA' , sysdate , sysdate , 'NO');
insert into "FACTURA" (id ,concepto , importe , numeroserie ,numerofactura , nifemisor , nombreemisor , nifreceptor , nombrereceptor,  numaries, numface ,puntoentrada, numregistrocontable , estado ,fechapresentacion , fechaemision , solanulacion) values (17 ,'Factura 17 de prueba', 1500 , '00017' , 'FACT-17' , '56995658Y' , 'el emisor' , '00000000T' , 'el receptor' , 'AR00017' , 'FAC00017' , 'PUEF' , '00001' , 'RECIBIDA' , sysdate , sysdate , 'NO');


--Creacion de los usuarios de prueba
insert into "USUARIO" (username, id, nombre, apellidos, mail , password) values ('SMA',1,'Alfonso' , 'Sanchez Martin' , 'asmartin@ayesa.com' , '$2a$10$RyY4bXtV3LKkDCutlUTYDOKd2AiJYZGp4Y7MPVdLzWzT1RX.JRZyG');
insert into "USUARIO" (username, id, nombre, apellidos, mail , password) values ('VJD',2,'Jesus' , 'Viruez Dominguez' , 'jviruez@ayesa.com' , '$2a$10$RyY4bXtV3LKkDCutlUTYDOKd2AiJYZGp4Y7MPVdLzWzT1RX.JRZyG');

insert into "ROL" (id, codigo, descripcion) values (1, 'ROLE_USER' , 'Usuario Gestor');
insert into "ROL" (id, codigo, descripcion) values (2, 'ROLE_ADMIN' , 'Usuario Administrador');

insert into "USER_X_ROLES" (fk_usu , fk_rol) values (1,1); 
insert into "USER_X_ROLES" (fk_usu , fk_rol) values (2,1);
insert into "USER_X_ROLES" (fk_usu , fk_rol) values (1,2);
insert into "USER_X_ROLES" (fk_usu , fk_rol) values (2,2);




